### ISSUE TITLE
Can't select disabled elements

### ISSUE THREAD

**Issue by jmalonzo** [GoogleChromeLabs/ProjectVisBug#188]
When an element has the *disabled* attribute set, it's unselectable. I think it would be if we can select disabled elements too.

**Comment by argyleink** [comment]
can you try using keyboard navigation to reach the node? select either it's parent or a sibling then tab to it? there are some tricky elements to select because i dont have full devtools power, generally a work around is to use keyboard nav to find the element. 
or, can you share a link to the button and i'll give it a peep?
thanks!

**Comment by jmalonzo** [comment]
Ah, yep that works. Thanks a lot!
