### ISSUE TITLE
Colors used for highlighting web elements are inaccessible

### ISSUE THREAD

**Issue by krisgardiner** [GoogleChromeLabs/ProjectVisBug#423]
**Screenshots:**
![screenshot](https://user-images.githubusercontent.com/34139730/71133386-6763f000-21c8-11ea-9e7e-857c8d0916b4.png)

![image](https://user-images.githubusercontent.com/34139730/71133362-5915d400-21c8-11ea-8f4e-ecc65f5191b2.png)

**Comment by argyleink** [comment]
Here's the LOC that needs improving https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js#L12

**Comment by aashu0148** [comment]
i want to work on this issue. I want to start contributing to open source i'm a frontend developer with 18months of experience. Can i work on it?

**Comment by argyleink** [comment]
sure! this bug is against the z-index plugin https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js

- clone the repo
- run `npm start`
- visit localhost:3000
- click the visbug search icon and search /zindex

your quest is to ensure the color assigned to the label won't make it hard to read, pretty at this loc https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js#L14

post here if you have any questions 👍

**Comment by aashu0148** [comment]
> sure! this bug is against the z-index plugin https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js
> 
> * clone the repo
> * run `npm start`
> * visit localhost:3000
> * click the visbug search icon and search /zindex
> 
> your quest is to ensure the color assigned to the label won't make it hard to read, pretty at this loc https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js#L14
> 
> post here if you have any questions 👍

okay thanks 👍

**Comment by aashu0148** [comment]
> sure! this bug is against the z-index plugin https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js
> 
> * clone the repo
> * run `npm start`
> * visit localhost:3000
> * click the visbug search icon and search /zindex
> 
> your quest is to ensure the color assigned to the label won't make it hard to read, pretty at this loc https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/plugins/zindex.js#L14
> 
> post here if you have any questions 👍

![Screenshot (32)](https://user-images.githubusercontent.com/71861291/99808825-720ccf00-2b67-11eb-8331-71c156f4f96e.png)

I got this error. What can be the issue ?

**Comment by argyleink** [comment]
`npm install` before `npm start` will work 👍

**Comment by aashu0148** [comment]
I can easily able to choose colors and apply them to the element see...
![Screenshot (33)](https://user-images.githubusercontent.com/71861291/99879817-4bb56500-2c35-11eb-9136-3cbb4859a2bd.png)

**Comment by aashu0148** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/71861291/99880980-dd74a080-2c3c-11eb-887b-d7c4fc0bdccc.png)
I think this edit button in left bottom is not working. Is this that issue ?

**Comment by aashu0148** [comment]
hey @argyleink  please tell

**Comment by argyleink** [comment]
Hi aashu0148! The task in this issue isn't around changing text colors or background colors with visbug, you're correct in reporting that those work as expected. It's the labels created by the z-index plugin that are in question:

![image](https://user-images.githubusercontent.com/1134620/99990713-042ff580-2d69-11eb-82d8-627685349df6.png)


This is why I'd sent a hint to the line of code in the plugin, since that's where it's creating the label colors and where a developer can create colors that have proper legibility contrast instead of "random". 

Success / completion of this task would mean a user can run the zindex plugin on many different pages and never see a label that fails wicg AA contrast scores.

**Comment by aashu0148** [comment]
@argyleink 
okay so I need make colors of the label to be of good legibility contrast and avoid colors with poor legibility. Is it so?
like in this picture the text in one label is hard to read.. so i need it to make readable by changing the color of the label. 
![Screenshot (35)](https://user-images.githubusercontent.com/71861291/100054914-01a4cd00-2e49-11eb-9a1a-a8c51635cc56.png)

**Comment by aashu0148** [comment]
hey @argyleink  I have done this. 
I have changed the logic of colors.
Now every color maintain the legibility;

**Comment by aashu0148** [comment]
hey @argyleink  I have made a pull request. Please review it :)

**Comment by aashu0148** [comment]
Hey @argyleink Please review the pull request

**Comment by aashu0148** [comment]
Hey @argyleink please reply

**Comment by argyleink** [comment]
Holidays! I'll check it out soon 👍🏻
