### ISSUE TITLE
Add no mouse days plugin

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#468]
https://github.com/marcysutton/no-mouse-days

Let VisBug load and init this on a page

**Comment by lavyda** [comment]
Hi, I'd like to help with this feature 🙂

**Comment by argyleink** [comment]
Awesome, thank you! ❤️ 

I can help streamline your work and offer a few pointers? like to this [wiki page](https://github.com/GoogleChromeLabs/ProjectVisBug/wiki/Plugins) 🙂 

I just tested that unpackage will allow us to grab the `no-mouse-days` npm package with https://unpkg.com/no-mouse-days@latest, which means you can pretty much copy the [tota11y](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/plugins/tota11y.js) plugin I think!

Let me know how it goes and how I can make it easier.

**Comment by lavyda** [comment]
Thanks for hints! I already created PR (#494)
Since plugin is enabled by default on [widow load](https://github.com/marcysutton/no-mouse-days/blob/main/index.js#L43) and we are loading module dynamically, I enabled it by explicitly calling `window.onload` function after importing module. Hopefully this solution is ok :blush:

**Comment by argyleink** [comment]
lovely work! works like a charm, so cool!
